### PR TITLE
Added depend_on_subset to match on subset of depend_on

### PR DESCRIPTION
**Pull request by StummeJ**
Useful if you want to TDD a rake file.

### CODE REVIEW

**Comment by crismali** [comment]
Thanks! Could you add a test for the matcher? Probably somewhere around here https://github.com/crismali/fantaskspec/blob/master/spec/lib/fantaskspec_spec.rb#L5

**Comment by StummeJ** [comment]
Added tests and fixed a typo.

**Comment by crismali** [comment]
Looks like there are some conflicts now. Sorry about that, after I saw your PR I went and added Travis CI and added new rspec versions to test against. Would you mind rebasing master underneath your changes?

**Comment by StummeJ** [comment]
Should be resolved now.

**Comment by crismali** [comment]
Awesome, thanks! I'll release this soon.

**Comment by crismali** [comment]
It's out.

**Pull request merged**
